name: test_workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - run: sudo apt-get install pandoc
      - uses: actions/checkout@v4
      - run: python -m nbconvert --to pdf lab_2.ipynb
