name: test_workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc texlive-xetex
      - run: python -m nbconvert --to pdf lab_2.ipynb --execute
      - uses: actions/upload_artifact@v4
      with:
        path: lab_2.pdf
      
